#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/okhotspots.jar:$APPDIR/lib/core.jar:$APPDIR/lib/oscP5.jar:$APPDIR/lib/SimpleOpenNI.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar" okhotspots
